
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
		#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"

/* event handler declarations */
void connection_view4_button5_onclicked(uib_view4_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_view4_create(Evas_Object* parent, void* create_callback_param) {
	uib_view4_view_context* vc = calloc(1, sizeof(uib_view4_view_context));
	vc->parent = parent;
	vc->view_name = "view4";
	vc->indicator_state = ELM_WIN_INDICATOR_SHOW;
	vc->is_user_view = false;
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	if (!vc->grid3) {
		vc->grid3= elm_grid_add(parent);
		vc->root_container = vc->grid3;
	}
	uib_views_get_instance()->set_targeted_view((uib_view_context*)vc);

	//bind event handler
	evas_object_smart_callback_add(vc->button5, "clicked", (Evas_Smart_Cb)connection_view4_button5_onclicked, vc);


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);

	return (uib_view_context*)vc;
}
void uib_view4_config_HD_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_view4_view_context* vc = (uib_view4_view_context*)uib_app_manager->find_view_context("view4");
	if(!vc) {
		return;
	}
	if(vc->grid3) {
		elm_grid_clear(vc->grid3, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid3, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid3, 1.0, 1.0);		elm_grid_size_set(vc->grid3, 480, 800);
		if (!vc->button5) {
			vc->button5 = elm_button_add(vc->grid3);
		}
		if (vc->button5) {
			evas_object_size_hint_align_set(vc->button5, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->button5, 1.0, 1.0);			elm_object_text_set(vc->button5,_UIB_LOCALE("Back"));
			elm_object_style_set(vc->button5,"default");
			evas_object_show(vc->button5);
		}
		if (!vc->entry2) {
			vc->entry2= elm_entry_add(vc->grid3);
		}
		if(vc->entry2) {
			elm_object_text_set(vc->entry2,_UIB_LOCALE("You can use this page template to move to the previous or next page."));
			elm_entry_single_line_set(vc->entry2, EINA_FALSE);
			elm_entry_password_set(vc->entry2, EINA_FALSE);
			elm_entry_editable_set(vc->entry2, EINA_FALSE);
			elm_entry_context_menu_disabled_set(vc->entry2, EINA_FALSE);
			elm_entry_scrollable_set(vc->entry2, EINA_FALSE);
			evas_object_size_hint_align_set(vc->entry2, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->entry2, 1.0, 1.0);
			elm_object_disabled_set(vc->entry2, EINA_FALSE);
			evas_object_show(vc->entry2);
		}
		if (!vc->bg2) {
			vc->bg2 = elm_bg_add(vc->grid3);
		}
		if(vc->bg2) {
			evas_object_size_hint_align_set(vc->bg2, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->bg2, 1.0, 1.0);			elm_bg_option_set(vc->bg2, (Elm_Bg_Option)ELM_BG_OPTION_SCALE);
			int hexValue = strtol("#266ABF"+1, NULL, 16);
			int r = (hexValue&0xFF0000)>>16;
			int g = (hexValue&0xFF00)>>8;
			int b = (hexValue&0xFF);
			elm_bg_color_set(vc->bg2, r, g, b);
			evas_object_show(vc->bg2);
		}
		if (!vc->label3) {
			vc->label3 = elm_label_add(vc->grid3);
		}
		if(vc->label3) {
			evas_object_size_hint_align_set(vc->label3, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->label3, 1.0, 1.0);			elm_object_text_set(vc->label3,_UIB_LOCALE("<font_size=32><color=#ffffff><b>Header</b></color></font_size>"));
			elm_label_line_wrap_set(vc->label3, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label3,0);
			elm_label_ellipsis_set(vc->label3, EINA_FALSE);
			evas_object_show(vc->label3);
		}
		elm_grid_pack(vc->grid3, vc->button5, 81, 729, 334, 47);		elm_grid_pack(vc->grid3, vc->entry2, 46, 95, 400, 520);		elm_grid_pack(vc->grid3, vc->bg2, 0, 0, 480, 60);		elm_grid_pack(vc->grid3, vc->label3, 43, 9, 384, 47);		evas_object_show(vc->grid3);
	}
}

